-- Create the contact_messages table
create table public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  phone text not null,
  company text,
  message text not null,
  page text,
  user_agent text,
  status text default 'new'
);

-- Enable Row Level Security (RLS)
alter table public.contact_messages enable row level security;

-- Create a policy to allow anonymous users to insert data
create policy "Enable insert for anonymous users"
on public.contact_messages
for insert
to anon
with check (true);

-- Create a policy to allow only authenticated users (admins) to view data
create policy "Enable read access for authenticated users only"
on public.contact_messages
for select
to authenticated
using (true);
